### ISSUE TITLE
Rename `.txt` file to `.txt.js` to enable syntax highlighting

### ISSUE THREAD

**Issue by eecavanna** [microbiomedata/notebook_hackathons#20]
### File

https://github.com/microbiomedata/notebook_hackathons/blob/soil-contig-tax/taxonomic_dist_by_soil_layer/python/mongodb_query.txt

### Syntax highlighting difference (excerpt)

As `.txt`:

```
db.getCollection("biosample_set").aggregate(
    [
        { $match: { 'soil_horizon': { '$in': ['O horizon', 'M horizon'] } } },
        {
            $project: {
                "id": 1,
                "soil_horizon": 1
            }
        },
```

As  `.js` (or `.txt.js` or `.anything.that.ends.with.js`):

```js
db.getCollection("biosample_set").aggregate(
    [
        { $match: { 'soil_horizon': { '$in': ['O horizon', 'M horizon'] } } },
        {
            $project: {
                "id": 1,
                "soil_horizon": 1
            }
        },
```

**Comment by eecavanna** [comment]
In this case, I like the suffix `.txt.js` as a way of signaling to the reader that this isn't a regular JavaScript script—it's a portion of one (something that can be copy/pasted into a MongoDB client).

**Comment by brynnz22** [comment]
Thanks Eric! I will change this. I wasn't sure how to save this query, but this is great to know.

**Comment by brynnz22** [comment]
Okay, this is changed and can be found here: https://github.com/microbiomedata/notebook_hackathons/blob/soil-contig-tax/taxonomic_dist_by_soil_layer/python/mongodb_query.txt.js. Thanks @eecavanna
